"""job_seeker/cover_letter.py — JD + experience bank -> cover letter DRAFT (Phase 4).

Offline, rule-based, no external API. Reuses the same bullet scoring as
``tailor`` to pull the strongest-matching experience, then assembles a
script-aware Markdown cover letter. The output is explicitly a DRAFT — the
user localizes and personalizes it (we never fabricate fluent prose in a
script we cannot verify).

Script-aware templates exist for LATIN (EN) and CJK (中文); other scripts fall
back to the LATIN template with a "localize to <script>" note, because we will
not pretend to generate correct Russian/Arabic/Hebrew prose without verification.
"""
from __future__ import annotations

from typing import Optional

from apply.mapping.jd_to_variant import detect_script, Script

from .tailor import parse_experience_bank, score_bullets, select_bullets

_TEMPLATES = {
    Script.LATIN: {
        "greeting": "Dear Hiring Manager,",
        "opening": "I am writing to express my interest in the opportunity described"
                   " in the attached posting. My background lines up with the role's"
                   " priorities, and I have included the most relevant experience below.",
        "closing_label": "Sincerely,",
    },
    Script.CJK: {
        "greeting": "尊敬的人力资源负责人：",
        "opening": "您好。就贵司发布的岗位，我认为自己的背景与该职位的诉求高度契合，"
                   "现将最相关的项目经历列示如下，供您参考。",
        "closing_label": "此致\n敬礼",
    },
}


def run_cover_letter(jd_text: str, bank_text: str, name: str = "",
                     jd_source: str = "", top_n: int = 5) -> str:
    """Return a Markdown cover-letter DRAFT string (script-aware)."""
    jd_script = detect_script(jd_text)
    tpl = _TEMPLATES.get(jd_script, _TEMPLATES[Script.LATIN])
    fallback_note = "" if jd_script in _TEMPLATES else (
        f"\n> NOTE: no native cover-letter template for script '{jd_script.value}'; "
        f"this is the LATIN template — localize to {jd_script.value} before sending.\n"
    )

    bullets = parse_experience_bank(bank_text)
    scored = score_bullets(bullets, jd_text)
    selected, fell_back = select_bullets(scored, top_n=top_n, per_role=3)

    matched: set = set()
    for _, _, m in selected:
        matched.update(m)
    matched_line = ", ".join(sorted(matched)[:12]) if matched else "—"

    lines = []
    lines.append("> DRAFT — review and personalize before sending. Generated by "
                 "job-seeker (offline, rule-based; no invented claims).")
    if fallback_note:
        lines.append(fallback_note)
    lines.append("")
    lines.append(f"# Cover Letter{' — ' + (jd_source or 'the role')}")
    lines.append("")
    lines.append(tpl["greeting"])
    lines.append("")
    lines.append(tpl["opening"])
    lines.append("")
    lines.append("**Relevant experience**")
    if selected:
        for b, score, _ in selected:
            lines.append(f"- {b.text}")
    else:
        lines.append("- (no experience-bank bullets matched this JD — add relevant "
                     "bullets to your experience bank, or review the JD keywords)")
    if fell_back:
        lines.append("")
        lines.append("> No bullets matched the JD's keywords; the items above are your "
                     "top bullets by recency/relevance — verify they fit before sending.")
    lines.append("")
    lines.append(f"**Areas of overlap with the posting:** {matched_line}")
    lines.append("")
    lines.append(tpl["closing_label"])
    if name:
        lines.append(name)
    return "\n".join(lines)


__all__ = ["run_cover_letter"]
